# -*- coding: utf-8 -*-
"""tweets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wcx_LRplSGBrkq4cgilqrzpGg63s6MBQ
"""

import tweepy
import pandas as pd

BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAAxW2wEAAAAAXuOyyK13uzw61JOScniUEmaeHuA%3D22iex5HLJPGPhFyHbfrOAicfqTI4GHMENCvpM5pwsVT7OBF7Ls"
client = tweepy.Client(bearer_token = BEARER_TOKEN)

query = "(burnout OR overwhelmed OR therapy OR hopeful OR calm OR healing OR depression OR depressed OR anger OR stress OR stressed OR nervous OR anxious) -is:retweet lang:en"
response = client.search_recent_tweets(query = query, tweet_fields = ["created_at", "text"], max_results = 100)

#create & fill DF
if response.data:
  tweets = [{"text": tweet.text, "created_at": tweet.created_at} for tweet in response.data]
  df = pd.DataFrame(tweets)
else:
  print("No tweets found")
  df = pd.DataFrame(columns = ["text", "created_at"])

#remove blank tweets, duplicates, retweets
df = df.dropna(subset = ['text'])
df = df[df['text'].str.strip() != '']
df = df[~df['text'].str.startswith("RT")]

df = df.drop_duplicates(subset=['text', 'created_at'])

#turn created_at into datetime object
df['created_at'] = pd.to_datetime(df['created_at'], errors = 'coerce')
df = df.dropna(subset=['created_at'])

df.to_csv("tweetsRaw.csv", index = False)

#tester
print(df)

from google.colab import files
files.download("tweetsRaw.csv")